-- =====================================================
-- CRM NEXUS - Schema Completo para Supabase
-- =====================================================
-- Ejecutar este script en el SQL Editor de Supabase
-- =====================================================
-- Enable UUID extension if not already enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
-- =====================================================
-- TABLA: crm_pipelines
-- Pipelines de ventas personalizables
-- =====================================================
CREATE TABLE public.crm_pipelines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    is_default BOOLEAN DEFAULT FALSE,
    currency TEXT DEFAULT 'EUR',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);
-- =====================================================
-- TABLA: crm_stages
-- Etapas dentro de cada pipeline (columnas del Kanban)
-- =====================================================
CREATE TABLE public.crm_stages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pipeline_id BIGINT REFERENCES public.crm_pipelines ON DELETE CASCADE NOT NULL,
    name TEXT NOT NULL,
    color TEXT DEFAULT 'indigo',
    position INTEGER NOT NULL DEFAULT 0,
    probability INTEGER DEFAULT 10,
    -- Probabilidad de cierre (0-100)
    is_won BOOLEAN DEFAULT FALSE,
    -- Etapa de éxito
    is_lost BOOLEAN DEFAULT FALSE,
    -- Etapa de pérdida
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);
-- =====================================================
-- TABLA: crm_companies
-- Empresas/Cuentas
-- =====================================================
CREATE TABLE public.crm_companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users NOT NULL,
    -- Información básica
    name TEXT NOT NULL,
    legal_name TEXT,
    tax_id TEXT,
    -- NIF/CIF/VAT
    -- Contacto
    email TEXT,
    phone TEXT,
    website TEXT,
    -- Dirección
    address_street TEXT,
    address_city TEXT,
    address_state TEXT,
    address_zip TEXT,
    address_country TEXT DEFAULT 'España',
    -- Clasificación
    industry TEXT,
    -- Sector/Industria
    company_size TEXT,
    -- 1-10, 11-50, 51-200, 201-500, 500+
    annual_revenue DECIMAL(15, 2),
    -- Ingresos anuales estimados
    -- Redes sociales
    linkedin_url TEXT,
    twitter_url TEXT,
    -- Metadata
    source TEXT,
    -- Fuente de adquisición
    notes TEXT,
    logo_url TEXT,
    -- Estado
    is_customer BOOLEAN DEFAULT FALSE,
    is_supplier BOOLEAN DEFAULT FALSE,
    is_active BOOLEAN DEFAULT TRUE,
    -- Timestamps
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);
-- =====================================================
-- TABLA: crm_contacts
-- Contactos individuales
-- =====================================================
CREATE TABLE public.crm_contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users NOT NULL,
    company_id BIGINT REFERENCES public.crm_companies ON DELETE
    SET NULL,
        -- Información personal
        first_name TEXT NOT NULL,
        last_name TEXT,
        email TEXT,
        phone TEXT,
        mobile TEXT,
        -- Información profesional
        job_title TEXT,
        -- Cargo
        department TEXT,
        -- Departamento
        -- Dirección (si diferente de empresa)
        address_street TEXT,
        address_city TEXT,
        address_state TEXT,
        address_zip TEXT,
        address_country TEXT,
        -- Redes sociales
        linkedin_url TEXT,
        twitter_url TEXT,
        -- Preferencias de contacto
        preferred_contact_method TEXT DEFAULT 'email',
        -- email, phone, whatsapp
        do_not_call BOOLEAN DEFAULT FALSE,
        do_not_email BOOLEAN DEFAULT FALSE,
        -- Clasificación
        lead_status TEXT DEFAULT 'new',
        -- new, contacted, qualified, proposal, negotiation, won, lost
        lead_source TEXT,
        -- web, referral, social, ads, event, cold_call
        lead_score INTEGER DEFAULT 0,
        -- Puntuación del lead (0-100)
        -- Avatar
        avatar_url TEXT,
        -- Metadata
        notes TEXT,
        birthday DATE,
        -- Estado
        is_active BOOLEAN DEFAULT TRUE,
        -- Timestamps
        last_contacted_at TIMESTAMP WITH TIME ZONE,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);
-- =====================================================
-- TABLA: crm_opportunities
-- Oportunidades de venta
-- =====================================================
CREATE TABLE public.crm_opportunities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users NOT NULL,
    pipeline_id BIGINT REFERENCES public.crm_pipelines ON DELETE CASCADE NOT NULL,
    stage_id BIGINT REFERENCES public.crm_stages ON DELETE
    SET NULL,
        contact_id BIGINT REFERENCES public.crm_contacts ON DELETE
    SET NULL,
        company_id BIGINT REFERENCES public.crm_companies ON DELETE
    SET NULL,
        -- Información de la oportunidad
        name TEXT NOT NULL,
        description TEXT,
        -- Valores económicos
        expected_revenue DECIMAL(15, 2) DEFAULT 0,
        -- Valor esperado
        probability INTEGER DEFAULT 10,
        -- Probabilidad de cierre (0-100)
        weighted_revenue DECIMAL(15, 2) GENERATED ALWAYS AS (expected_revenue * probability / 100) STORED,
        -- Fechas
        expected_close_date DATE,
        actual_close_date DATE,
        -- Clasificación
        priority TEXT DEFAULT 'medium',
        -- low, medium, high, urgent
        source TEXT,
        -- Fuente de la oportunidad
        -- Estado
        is_won BOOLEAN DEFAULT FALSE,
        is_lost BOOLEAN DEFAULT FALSE,
        lost_reason TEXT,
        -- Posición en el Kanban
        position INTEGER DEFAULT 0,
        -- Metadata
        notes TEXT,
        -- Timestamps
        created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);
-- =====================================================
-- TABLA: crm_activities
-- Actividades programadas (llamadas, reuniones, tareas)
-- =====================================================
CREATE TABLE public.crm_activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users NOT NULL,
    -- Relaciones (al menos una debe estar presente)
    contact_id BIGINT REFERENCES public.crm_contacts ON DELETE CASCADE,
    company_id BIGINT REFERENCES public.crm_companies ON DELETE CASCADE,
    opportunity_id BIGINT REFERENCES public.crm_opportunities ON DELETE CASCADE,
    -- Tipo de actividad
    activity_type TEXT NOT NULL DEFAULT 'task',
    -- call, meeting, email, task, note, deadline
    -- Información
    title TEXT NOT NULL,
    description TEXT,
    -- Programación
    due_date TIMESTAMP WITH TIME ZONE,
    duration_minutes INTEGER DEFAULT 30,
    -- Estado
    is_done BOOLEAN DEFAULT FALSE,
    completed_at TIMESTAMP WITH TIME ZONE,
    -- Prioridad
    priority TEXT DEFAULT 'normal',
    -- low, normal, high, urgent
    -- Resultado (para llamadas/reuniones)
    outcome TEXT,
    -- successful, no_answer, left_message, rescheduled
    outcome_notes TEXT,
    -- Timestamps
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);
-- =====================================================
-- TABLA: crm_notes
-- Notas/Comentarios tipo "chatter"
-- =====================================================
CREATE TABLE public.crm_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users NOT NULL,
    -- Relaciones (al menos una debe estar presente)
    contact_id BIGINT REFERENCES public.crm_contacts ON DELETE CASCADE,
    company_id BIGINT REFERENCES public.crm_companies ON DELETE CASCADE,
    opportunity_id BIGINT REFERENCES public.crm_opportunities ON DELETE CASCADE,
    -- Contenido
    content TEXT NOT NULL,
    -- Tipo de nota
    note_type TEXT DEFAULT 'note',
    -- note, call_log, email_log, meeting_log, system
    -- Metadata
    is_pinned BOOLEAN DEFAULT FALSE,
    -- Timestamps
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);
-- =====================================================
-- TABLA: crm_tags
-- Etiquetas para clasificación
-- =====================================================
CREATE TABLE public.crm_tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users NOT NULL,
    name TEXT NOT NULL,
    color TEXT DEFAULT 'blue',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    UNIQUE(user_id, name)
);
-- Tablas de relación para etiquetas (many-to-many)
CREATE TABLE public.crm_contact_tags (
    contact_id BIGINT REFERENCES public.crm_contacts ON DELETE CASCADE,
    tag_id BIGINT REFERENCES public.crm_tags ON DELETE CASCADE,
    PRIMARY KEY (contact_id, tag_id)
);
CREATE TABLE public.crm_company_tags (
    company_id BIGINT REFERENCES public.crm_companies ON DELETE CASCADE,
    tag_id BIGINT REFERENCES public.crm_tags ON DELETE CASCADE,
    PRIMARY KEY (company_id, tag_id)
);
CREATE TABLE public.crm_opportunity_tags (
    opportunity_id BIGINT REFERENCES public.crm_opportunities ON DELETE CASCADE,
    tag_id BIGINT REFERENCES public.crm_tags ON DELETE CASCADE,
    PRIMARY KEY (opportunity_id, tag_id)
);
-- =====================================================
-- TABLA: crm_products
-- Productos/Servicios para cotizaciones
-- =====================================================
CREATE TABLE public.crm_products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    sku TEXT,
    -- Código de producto
    -- Precios
    unit_price DECIMAL(15, 2) DEFAULT 0,
    cost_price DECIMAL(15, 2) DEFAULT 0,
    -- Categorización
    category TEXT,
    -- Estado
    is_active BOOLEAN DEFAULT TRUE,
    -- Timestamps
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);
-- =====================================================
-- TABLA: crm_opportunity_products
-- Productos asociados a oportunidades (líneas de cotización)
-- =====================================================
CREATE TABLE public.crm_opportunity_products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    opportunity_id BIGINT REFERENCES public.crm_opportunities ON DELETE CASCADE NOT NULL,
    product_id BIGINT REFERENCES public.crm_products ON DELETE
    SET NULL,
        -- Puede ser producto personalizado (sin product_id)
        product_name TEXT NOT NULL,
        description TEXT,
        -- Cantidades y precios
        quantity DECIMAL(10, 2) DEFAULT 1,
        unit_price DECIMAL(15, 2) DEFAULT 0,
        discount_percent DECIMAL(5, 2) DEFAULT 0,
        tax_percent DECIMAL(5, 2) DEFAULT 21,
        -- IVA por defecto 21%
        -- Totales calculados
        subtotal DECIMAL(15, 2) GENERATED ALWAYS AS (
            quantity * unit_price * (1 - discount_percent / 100)
        ) STORED,
        total DECIMAL(15, 2) GENERATED ALWAYS AS (
            quantity * unit_price * (1 - discount_percent / 100) * (1 + tax_percent / 100)
        ) STORED,
        -- Posición en la lista
        position INTEGER DEFAULT 0,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);
-- =====================================================
-- TABLA: crm_email_templates
-- Plantillas de email
-- =====================================================
CREATE TABLE public.crm_email_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users NOT NULL,
    name TEXT NOT NULL,
    subject TEXT NOT NULL,
    body TEXT NOT NULL,
    -- Variables disponibles: {{contact_name}}, {{company_name}}, etc.
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);
-- =====================================================
-- ÍNDICES para mejor rendimiento
-- =====================================================
CREATE INDEX idx_crm_contacts_user ON public.crm_contacts(user_id);
CREATE INDEX idx_crm_contacts_company ON public.crm_contacts(company_id);
CREATE INDEX idx_crm_contacts_status ON public.crm_contacts(lead_status);
CREATE INDEX idx_crm_contacts_email ON public.crm_contacts(email);
CREATE INDEX idx_crm_companies_user ON public.crm_companies(user_id);
CREATE INDEX idx_crm_companies_name ON public.crm_companies(name);
CREATE INDEX idx_crm_opportunities_user ON public.crm_opportunities(user_id);
CREATE INDEX idx_crm_opportunities_pipeline ON public.crm_opportunities(pipeline_id);
CREATE INDEX idx_crm_opportunities_stage ON public.crm_opportunities(stage_id);
CREATE INDEX idx_crm_opportunities_contact ON public.crm_opportunities(contact_id);
CREATE INDEX idx_crm_opportunities_company ON public.crm_opportunities(company_id);
CREATE INDEX idx_crm_activities_user ON public.crm_activities(user_id);
CREATE INDEX idx_crm_activities_due ON public.crm_activities(due_date);
CREATE INDEX idx_crm_activities_contact ON public.crm_activities(contact_id);
CREATE INDEX idx_crm_activities_opportunity ON public.crm_activities(opportunity_id);
CREATE INDEX idx_crm_notes_contact ON public.crm_notes(contact_id);
CREATE INDEX idx_crm_notes_opportunity ON public.crm_notes(opportunity_id);
-- =====================================================
-- ROW LEVEL SECURITY (RLS)
-- =====================================================
-- Pipelines
ALTER TABLE public.crm_pipelines ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own pipelines" ON public.crm_pipelines FOR
SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own pipelines" ON public.crm_pipelines FOR
INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own pipelines" ON public.crm_pipelines FOR
UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own pipelines" ON public.crm_pipelines FOR DELETE USING (auth.uid() = user_id);
-- Stages
ALTER TABLE public.crm_stages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view stages of own pipelines" ON public.crm_stages FOR
SELECT USING (
        EXISTS (
            SELECT 1
            FROM public.crm_pipelines
            WHERE crm_pipelines.id = crm_stages.pipeline_id
                AND crm_pipelines.user_id = auth.uid()
        )
    );
CREATE POLICY "Users can insert stages to own pipelines" ON public.crm_stages FOR
INSERT WITH CHECK (
        EXISTS (
            SELECT 1
            FROM public.crm_pipelines
            WHERE crm_pipelines.id = pipeline_id
                AND crm_pipelines.user_id = auth.uid()
        )
    );
CREATE POLICY "Users can update stages of own pipelines" ON public.crm_stages FOR
UPDATE USING (
        EXISTS (
            SELECT 1
            FROM public.crm_pipelines
            WHERE crm_pipelines.id = crm_stages.pipeline_id
                AND crm_pipelines.user_id = auth.uid()
        )
    );
CREATE POLICY "Users can delete stages of own pipelines" ON public.crm_stages FOR DELETE USING (
    EXISTS (
        SELECT 1
        FROM public.crm_pipelines
        WHERE crm_pipelines.id = crm_stages.pipeline_id
            AND crm_pipelines.user_id = auth.uid()
    )
);
-- Companies
ALTER TABLE public.crm_companies ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own companies" ON public.crm_companies FOR
SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own companies" ON public.crm_companies FOR
INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own companies" ON public.crm_companies FOR
UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own companies" ON public.crm_companies FOR DELETE USING (auth.uid() = user_id);
-- Contacts
ALTER TABLE public.crm_contacts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own contacts" ON public.crm_contacts FOR
SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own contacts" ON public.crm_contacts FOR
INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own contacts" ON public.crm_contacts FOR
UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own contacts" ON public.crm_contacts FOR DELETE USING (auth.uid() = user_id);
-- Opportunities
ALTER TABLE public.crm_opportunities ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own opportunities" ON public.crm_opportunities FOR
SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own opportunities" ON public.crm_opportunities FOR
INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own opportunities" ON public.crm_opportunities FOR
UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own opportunities" ON public.crm_opportunities FOR DELETE USING (auth.uid() = user_id);
-- Activities
ALTER TABLE public.crm_activities ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own activities" ON public.crm_activities FOR
SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own activities" ON public.crm_activities FOR
INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own activities" ON public.crm_activities FOR
UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own activities" ON public.crm_activities FOR DELETE USING (auth.uid() = user_id);
-- Notes
ALTER TABLE public.crm_notes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own notes" ON public.crm_notes FOR
SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own notes" ON public.crm_notes FOR
INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own notes" ON public.crm_notes FOR
UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own notes" ON public.crm_notes FOR DELETE USING (auth.uid() = user_id);
-- Tags
ALTER TABLE public.crm_tags ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own tags" ON public.crm_tags FOR
SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own tags" ON public.crm_tags FOR
INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own tags" ON public.crm_tags FOR
UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own tags" ON public.crm_tags FOR DELETE USING (auth.uid() = user_id);
-- Tag relations (inherit from parent)
ALTER TABLE public.crm_contact_tags ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage contact tags" ON public.crm_contact_tags FOR ALL USING (
    EXISTS (
        SELECT 1
        FROM public.crm_contacts
        WHERE crm_contacts.id = contact_id
            AND crm_contacts.user_id = auth.uid()
    )
);
ALTER TABLE public.crm_company_tags ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage company tags" ON public.crm_company_tags FOR ALL USING (
    EXISTS (
        SELECT 1
        FROM public.crm_companies
        WHERE crm_companies.id = company_id
            AND crm_companies.user_id = auth.uid()
    )
);
ALTER TABLE public.crm_opportunity_tags ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage opportunity tags" ON public.crm_opportunity_tags FOR ALL USING (
    EXISTS (
        SELECT 1
        FROM public.crm_opportunities
        WHERE crm_opportunities.id = opportunity_id
            AND crm_opportunities.user_id = auth.uid()
    )
);
-- Products
ALTER TABLE public.crm_products ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own products" ON public.crm_products FOR
SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own products" ON public.crm_products FOR
INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own products" ON public.crm_products FOR
UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own products" ON public.crm_products FOR DELETE USING (auth.uid() = user_id);
-- Opportunity Products (inherit from opportunity)
ALTER TABLE public.crm_opportunity_products ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage opportunity products" ON public.crm_opportunity_products FOR ALL USING (
    EXISTS (
        SELECT 1
        FROM public.crm_opportunities
        WHERE crm_opportunities.id = opportunity_id
            AND crm_opportunities.user_id = auth.uid()
    )
);
-- Email Templates
ALTER TABLE public.crm_email_templates ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own templates" ON public.crm_email_templates FOR
SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own templates" ON public.crm_email_templates FOR
INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own templates" ON public.crm_email_templates FOR
UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own templates" ON public.crm_email_templates FOR DELETE USING (auth.uid() = user_id);
-- =====================================================
-- FUNCIÓN: Crear pipeline por defecto para nuevos usuarios
-- =====================================================
CREATE OR REPLACE FUNCTION public.create_default_crm_pipeline() RETURNS TRIGGER AS $$
DECLARE new_pipeline_id BIGINT;
BEGIN -- Crear pipeline por defecto
INSERT INTO public.crm_pipelines (user_id, name, description, is_default)
VALUES (
        NEW.id,
        'Pipeline Principal',
        'Pipeline de ventas predeterminado',
        TRUE
    )
RETURNING id INTO new_pipeline_id;
-- Crear etapas por defecto
INSERT INTO public.crm_stages (
        pipeline_id,
        name,
        color,
        position,
        probability,
        is_won,
        is_lost
    )
VALUES (
        new_pipeline_id,
        'Nuevo',
        'slate',
        0,
        10,
        FALSE,
        FALSE
    ),
    (
        new_pipeline_id,
        'Calificado',
        'blue',
        1,
        20,
        FALSE,
        FALSE
    ),
    (
        new_pipeline_id,
        'Propuesta',
        'purple',
        2,
        40,
        FALSE,
        FALSE
    ),
    (
        new_pipeline_id,
        'Negociación',
        'amber',
        3,
        60,
        FALSE,
        FALSE
    ),
    (
        new_pipeline_id,
        'Ganado',
        'emerald',
        4,
        100,
        TRUE,
        FALSE
    ),
    (
        new_pipeline_id,
        'Perdido',
        'red',
        5,
        0,
        FALSE,
        TRUE
    );
RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
-- Trigger para crear pipeline cuando se crea un usuario
CREATE TRIGGER on_crm_user_created
AFTER
INSERT ON public.profiles FOR EACH ROW EXECUTE PROCEDURE public.create_default_crm_pipeline();
-- =====================================================
-- FUNCIÓN: Actualizar updated_at automáticamente
-- =====================================================
CREATE OR REPLACE FUNCTION public.update_updated_at_column() RETURNS TRIGGER AS $$ BEGIN NEW.updated_at = TIMEZONE('utc'::text, NOW());
RETURN NEW;
END;
$$ LANGUAGE plpgsql;
-- Aplicar trigger a todas las tablas CRM
CREATE TRIGGER update_crm_pipelines_updated_at BEFORE
UPDATE ON public.crm_pipelines FOR EACH ROW EXECUTE PROCEDURE public.update_updated_at_column();
CREATE TRIGGER update_crm_companies_updated_at BEFORE
UPDATE ON public.crm_companies FOR EACH ROW EXECUTE PROCEDURE public.update_updated_at_column();
CREATE TRIGGER update_crm_contacts_updated_at BEFORE
UPDATE ON public.crm_contacts FOR EACH ROW EXECUTE PROCEDURE public.update_updated_at_column();
CREATE TRIGGER update_crm_opportunities_updated_at BEFORE
UPDATE ON public.crm_opportunities FOR EACH ROW EXECUTE PROCEDURE public.update_updated_at_column();
CREATE TRIGGER update_crm_activities_updated_at BEFORE
UPDATE ON public.crm_activities FOR EACH ROW EXECUTE PROCEDURE public.update_updated_at_column();
CREATE TRIGGER update_crm_notes_updated_at BEFORE
UPDATE ON public.crm_notes FOR EACH ROW EXECUTE PROCEDURE public.update_updated_at_column();
CREATE TRIGGER update_crm_products_updated_at BEFORE
UPDATE ON public.crm_products FOR EACH ROW EXECUTE PROCEDURE public.update_updated_at_column();
CREATE TRIGGER update_crm_email_templates_updated_at BEFORE
UPDATE ON public.crm_email_templates FOR EACH ROW EXECUTE PROCEDURE public.update_updated_at_column();